name = "horas-push"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[kv_namespaces]]
binding = "PUSH_STORE"
id = "62bd1417d6a54100927a6672468b4c1b"

[triggers]
crons = ["*/30 * * * *"]
